apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: job
  name: job
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: job
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: job
    spec:
      containers:
        - image: job
          name: data-inn
          resources: {}
      restartPolicy: Always
status: {}
